name: WinForms App CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-build:
    uses: SampleProjectDotNet/reusable-workflows/.github/workflows/dotnet-build-test.yml@main
    with:
      projectType: "WindowsForm"
    secrets: inherit
  
  call-publish:
    needs: call-build
    uses: SampleProjectDotNet/reusable-workflows/.github/workflows/publish-to-file-server.yml@main
    secrets: inherit